// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "../components/Home.js";
import * as React from "react";

function Page$default(props) {
  return React.createElement(Home.make, {});
}

var $$default = Page$default;

export {
  $$default ,
  $$default as default,
}
/* Home Not a pure module */
