// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home(props) {
  return React.createElement("div", {
              className: "w-full h-screen flex justify-center items-center"
            }, React.createElement("h1", {
                  className: "text-3xl"
                }, "Hello World"));
}

var make = Home;

export {
  make ,
}
/* react Not a pure module */
